[package]
name = "impacted"
version = "0.0.0"
license = "Unlicense"
authors = ["Jonathan Cornaz"]
edition = "2021"
rust-version = "1.58"
description = "2d collision test for arbitrary convex shapes"
repository = "https://github.com/jcornaz/impacted"
categories = ["game-development"]
keywords = ["collision", "convex", "geometry", "gamedev", "gjk"]

[features]
default = ["std"]
std = ["glam/std", "thiserror"]

[dependencies]
# Public
glam = { version = "0.20.2", default-features = false, features = ["libm"] }
bevy_transform = { version = "0.6.0", default-features = false, optional = true }

# Private
thiserror = { version = "1.0", default-features = false, optional = true }

[dev-dependencies]
rstest = "0.12.0"
