[package]
name = "gjk2d"
version = "0.0.0"
license = "Unlicense"
authors = ["Jonathan Cornaz"]
edition = "2021"
rust-version = "1.58"
description = "2d collision test for arbitrary convex shapes "
repository = "https://github.com/jcornaz/gjk2d"
categories = ["game-development"]
keywords = ["collision", "convex", "geometry", "gamedev", "gjk"]


[dependencies]


[dev-dependencies]

